from .constants import (
    GEOTEXT_PREPROCESSED_DATA,
    GEOTEXT_RAW_DATA,
    TWITTER_PREPROCESSED_DATA,
    TWITTER_RAW_DATA,
    TWITTER_EDGE_PATH,
    TWITTER_GRAPH_PATH,
    TWITTER_GRAPH_MODEL_PATH,
    TWITTER_LANGUAGE_MODEL_PATH,
    TWITTER_LM_DATA_PATH,
    TWITTER_LM_TRAINING_RESULT_PATH,
    device,
    seed
)

print("constants/__init__.py loaded successfully")
